Finished up db stuff
 - script almost done...

diff --git a/ChangeCSHAccountName b/ChangeCSHAccountName
--- a/ChangeCSHAccountName
+++ b/ChangeCSHAccountName
@@ -10,6 +10,10 @@
 #
 # 12/2010 - worr 	Original version
 
+# Exits on non-zero line
+# Thanks Russ! That's pretty baller
+set -e
+
 if [[ $# -ne 2 ]]; then
 	echo "Usage: $0 <old username> <new username>"
 	exit 1
@@ -37,6 +41,8 @@ OLD_HOMEDIR=$(ypmatch $OLD_USERNAME passwd | cut -d: -f6)
 NEW_HOMDIR=$(echo $OLD_HOMEDIR | sed -e "s/$OLD_USERNAME/$NEW_USERNAME/")
 OLD_KERB5_PRINC="$OLD_USERNAME@CSH.RIT.EDU"
 NEW_KERB5_PRINC="$NEW_USERNAME@CSH.RIT.EDU"
+OLD_WIKINAME=$(perl -e 'print ucfirst($OLD_USERNAME);') # Hahaha, using Perl for this shit #overkill
+NEW_WIKINAME=$(perl -e 'print ucfirst($NEW_USERNAME);')
 
 LDAP_SERVER="ldap.csh.rit.edu"
 KADMIN_CMD="/usr/bin/kadmin -p $KADMIN_USER/admin -q "
@@ -89,7 +95,6 @@ mail: $NEW_USERNAME@csh.rit.edu" | ldapmodify -Q -h $LDAP_SERVER
 
 change_krb5_entry () {
 	echo "Changing kerberos princ..." | tee -a $LOG_FILE
-	$KADMIN_CMD "modprinc -expire now $OLD_USERNAME"
 	$KADMIN_CMD "delprinc -force $OLD_USERNAME"
 	$KADMIN_CMD "ank $NEW_USERNAME"
 
@@ -102,7 +107,7 @@ change_krb5_entry () {
 }
 
 move_home_directory () {
-	echo "Moving home directory..."
+	echo "Moving home directory..." | tee -a $LOG_FILE
 	if [[ -d $NEW_HOMDIR ]]; then
 		echo "$NEW_HOMDIR already exists!?" | tee -a $LOG_FILE
 		return 1
@@ -116,7 +121,35 @@ move_home_directory () {
 		return 1
 	fi
 
-	echo "Successfully moved home directory"
+	echo "Successfully moved home directory" | tee -a $LOG_FILE
 }
 
+change_db_entries () {
+	echo "You will be prompted once for the root db password, and then start's net_user password. Steel yourself."
+
+	# Change wiki username
+	echo "Changing wiki username..." | tee -a $LOG_FILE
+	mysql -u root -p wikidb -e "UPDATE user SET user_name = '$NEW_WIKINAME' WHERE user_name = '$OLD_WIKINAME';" -h db
+
+	if [[ $? -ne 0 ]]; then
+		echo "Couldn't change wiki usename" | tee -a $LOG_FILE
+		return 1
+	fi
+
+	echo "Successfully changed wiki username" | tee -a $LOG_FILE
+
+	echo "Changing username in start..." | tee -a $LOG_FILE
+	psql -U net_user -c "UPDATE hosts SET username = '$NEW_USERNAME' WHERE username = '$OLD_USERNAME';" -h db network
+
+	if [[ $? -ne 0 ]]; then
+		echo "Couldn't change username in start" | tee -a $LOG_FILE
+		return 1
+	fi
+
+	echo "Successfully changed start username" | tee -a $LOG_FILE
+}
+
+change_ldap_entry
+change_krb5_entry
 move_home_directory
+change_db_entries
